import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Sidebar } from "./components/layout/Sidebar"
import { FollowBar } from "./components/layout/FollowBar"
import { LoginModal } from "./components/modals/LoginModal "
import { RegisterModal } from "./components/modals/RegisterModal"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Red Cloud | Twitter (X) Clone",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <RegisterModal />
          <LoginModal />
          <div className="h-screen bg-slate-50">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />
                <div className="col-span-3 lg:col-span-2 border-x-[2px]">
                  {children}
                </div>
                <FollowBar />
              </div>
            </div>
          </div>
        </body>
      </html>
    </>
  )
}
